### PR TITLE
Add rename of 'paperwork-gui' -> 'paperwork'

### PR DESCRIPTION
**Pull request by maikwoehl**
https://dev.getsol.us/D11825

### CODE REVIEW

**Review by JoshStrobl — CHANGES_REQUESTED** [review]
Currently has merge conflicts and needs rebasing.

**Comment by joebonrichie** [comment]
The whitespace is wrong - please check your spaces/tabs settings

**Comment by maikwoehl** [comment]
> The whitespace is wrong - please check your spaces/tabs settings

Ahh... sorry. Is fixed.

**Comment by joebonrichie** [comment]
And can you merge into a single commit please :D

**Pull request merged**
