### PR TITLE
Added additional items to Third Party section.

### PR DESCRIPTION
**Pull request by HarveyDevel**
- AnyDesk
- CLion
- DataGrip
- Franz
- Microsoft Core Fonts
- PHPStorm
- Pixeluvo
- Pomodoneapp
- Scrivener
- Spideroak
- Sunvox
- Synology Cloud Station Drive
- TeamViewer

### CODE REVIEW

**Comment by TheHarveyBirdman** [comment]
Not sure how much interest there is in adding these missing items to the third party section. But, I couldn't sleep and wanted to learn/tinker so...

Here are the issues as it stands:
+ Sunvox needs to be fixed, it currently won't install, fails the hash check. https://github.com/getsolus/3rd-party/issues/19
+ Spideroak will install but the install button doesn't change to "check for updates" like the rest do.

I added to the third party section of the package.yml for papirus-icon-theme but the following don't seem to have icons:
- Pomodoneapp (Has an icon but doesn't seem to work)
- mscorefonts
- Pixeluvo
- Scrivner
- Sunvox

**Comment by Staudey** [comment]
Spideroak doesn't show up as installed because its actual name is "spideroakone", not "spideroak"

**Comment by Staudey** [comment]
```
'spideroakone':
        ('spideroakone', 'SpiderOakONE',
```

is how it should look

**Comment by Staudey** [comment]
The PomoDoneApp icon shows up if you capitalize it properly

```
    'pomodoneapp':
        ('PomoDoneApp', 'PomoDoneApp',
         'Workflow tracker using Pomodoro technique',
         'office/pomodoneapp/pspec.xml'),
```

https://i.imgur.com/eyoN5yr.png

**Comment by TheHarveyBirdman** [comment]
@Staudey Thanks for the help :)

**Comment by Vistaus** [comment]
I'm sorry if I'm crossing a line here, but doesn't this pull request belong on the 3rd party repo https://github.com/getsolus/3rd-party ? Just curious.

**Comment by Staudey** [comment]
Nope. The items are already in the repository, just not shown in the
Software Center

**Pull request closed without merging**
