### PR TITLE
Deprecate orphan python2 modules and duplicate packages 

### PR DESCRIPTION
**Pull request by algent-al**

### CODE REVIEW

**Comment by algent-al** [comment]
`ansi-terminal` is a dublicate of `haskell-ansi-terminal`
`colord-gtk ` is a duplicate of `libcolord-gtk`

**Comment by joebonrichie** [comment]
I would personally leave a special comment for python-urlgrabber, since it used to be used for pisi. Otherwise, great work as usual.

**Comment by algent-al** [comment]
You are right @joebonrichie. Done!

**Comment by DataDrake** [comment]
LGTM. Thanks!

**Pull request merged**
